# Unit 14

In [1]:
from datascience import *
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [4]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [5]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [6]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [7]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [8]:
positive_terms = 1 / positive_term_denominators

In [9]:
negative_terms = 1 / (positive_term_denominators + 2)

In [10]:
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

In [11]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [12]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728)
lows

array([2.128, 2.371, 2.874, 3.728])

In [13]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([11.472, 12.016, 11.711, 11.436])

In [14]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [15]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [16]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143