# Unit 13

In [4]:
from datascience import *
import numpy as np

In [5]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [6]:
sum(highs)/len(highs)

14.434000000000001

In [7]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [8]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [9]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [10]:
highs.size

4

In [11]:
highs.sum()

57.736000000000004

In [12]:
highs.mean()

14.434000000000001

In [13]:
np.diff(highs)

array([0.787, 0.198, 0.579])